# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links
- weibo

# Links
links:
  Psychokinesis: http://psychokinesis.me/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: covertness

# Baidu share
baidushare: true